spring:
  application:
    name: log-tracing

server:
  port: 50018

eureka:
  client:
    service-url:
      defaultZone: http://localhost:50020/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,loggers,prometheus

logging:
  level:
    root: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss,UTC} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /Users/collenkim/log-tracing/promtail/logs/log-tracing/app.log
  logback:
    rolling-policy:
      max-file-size: 10MB
      max-history: 7

otel:
  exporter:
    otlp:
      protocol: grpc
      endpoint: http://localhost:4317
  traces:
    exporter: otlp
  logs:
    exporter: none
  resource:
    attributes:
      service.name: logtracing-service